### ISSUE TITLE
Move contents to Zenodo and archive this repository?

### ISSUE THREAD

**Issue by pllim** [astropy/archived-documentation#2]
See https://github.com/astropy/astropy-project/issues/243

**Comment by astrofrog** [comment]
Don't we use this to serve the old versions on RTD? I will double check

**Comment by pllim** [comment]
Hard to tell from the RTD settings. I only see tarballs here. Please do report back. Thanks!

**Comment by pllim** [comment]
> Don't we use this to serve the old versions on RTD? I will double check

@astrofrog , what did you find? 🙏

**Comment by astrofrog** [comment]
We use it here: https://github.com/astropy/astropy/tree/older-docs-archive

**Comment by pllim** [comment]
Okay then... Thanks!
